### PR TITLE
Updated SecurityContext with clarifications in javadoc, renamed method

### PR DESCRIPTION
**Pull request by arjantijms**

### CODE REVIEW

**Review by ggam — COMMENTED** [review]
How are multiple url patterns expected to be passed? Separated by commas? If that's the case, an example on the JavaDoc would be handy.

Also, it should be stated that it must return false when the pattern does not exist. Now it only talks about an application "with no resources at all" I think.

**Review by wmhopkins — CHANGES_REQUESTED** [review]
I think we're better off leaving it as resource (or "url") for now -- moving from checking a single resource to checking multiple resources adds complexity, rather than reducing it. The context for this call will most often be a check for access to a specific URL.

For the method that takes HTTP methods as parameters, would it be better to pass a Set, or an array, rather than use varargs? Seems like that would make the implementation code simpler.

Prefer the original name instead of hasCallerAccessToXXX().

**Comment by arjantijms** [comment]
@ggam 
That's a good question, and it's basically explained by the link to WebResourcePermission:

 * URLPatternList ::= URLPattern | URLPatternList colon URLPattern
 * URLPatternSpec ::= null | URLPattern | URLPattern colon URLPatternList

So simply said the separator is a colon ;)

**Comment by ggam** [comment]
Thanks! In that case, the example will be specially helpful. Although I'm
with Will in that accepting just one url would be enough for most cases.
What's the use case for taking multiple resources at once?

**Comment by wmhopkins** [comment]
I still feel like the API should be testing a specific resource, not a list of arbitrary URL patterns that could each match multiple URLs. I can see that something like that might be useful, but at that point it's really policy analysis, not policy evaluation. To make a simple access decision, one needs to know only the specific resource the user is attempting to access. It might be efficient to test several resources at once in some cases, but URL patterns seems like overkill, and it's easy enough to test resources one at a time. Let's keep it simple for now.

**Pull request closed without merging**
