### PR TITLE
Publish JavaDoc to GitHub Pages

### PR DESCRIPTION
**Pull request by ggam**
Branch "gh-pages" needs to be created before the "scm-publish:publish-scm" can be called. Results will then be available at https://javaee-security-spec.github.io/security-api/

Travis should be configured to run that goal for each merged pull request.

### CODE REVIEW

**Comment by keilw** [comment]
@ggam Are you a JCP or EG member (of JSR 375) already?

**Comment by ggam** [comment]
Not exactly. I just signed the OCA for Soteria. Thought that would suffice.

**Comment by keilw** [comment]
Thanks, I asked on the mailing list, but if Spec Lead Oracle is fine with the OCA for all artifacts you should be good.

**Comment by wmhopkins** [comment]
@ggam It looks like you've signed the contributor agreement so we should be all set -- would be good if you also joined the JSR as an expert or contributor, though -- I sent you email about it.

Can you explain why this needs to be run on a separate branch (gh-pages)? Couldn't it run off of the master branch?

**Comment by keilw** [comment]
@ggam Depending on what level of involvement you wish and e.g. if you are employed or self-employed, you could join as Full JCP Member or the new "Associate" category. Full Members can also join this or other Expert Groups, Associates are equally welcome to participate as "Contributors", e.g. the 3 we already got on https://jcp.org/en/jsr/detail?id=375
Please ask me or the PMO if you consider joining the JCP and have further questions.

**Comment by ggam** [comment]
@wmhopkins I'm currently in the process to become a JCP Associate. Today I signed the document and AFAIK, now I just have to wait for Oracle to sign the other side of the agreement. I also requested to become a JSR contributor today, but I guess my JCP membership needs to be in place first.

As for the gh-pages thing: GitHub enables a website per project under the domain https://{projectname}.github.io/{repositoryname}
For the content, it searches for a special "gh-pages" branch, and serves what it finds there.

So the Maven task has to be run from the master branch, but the maven-scm-publish-plugin will push javadoc to the gh-pages, (which needs to exist beforehand).

@keilw Thanks! I have one question from what I see on https://jcp.org/en/participation/membership
If I'm employed but my company is not interested in becoming part of the JCP, but my I contribute in my free time, may I still become a full member?

**Comment by wmhopkins** [comment]
@ggam I approved your nomination for JSR-375; might be better to continue the JCP discussion on email rather than here.

I've created the gh-pages branch and will merge this pull request. It looks like we can select what branch to publish to github pages though -- is there any value to using a branch other than master if we're going to publish on every submit to master?

**Comment by keilw** [comment]
@ggam @wmhopkins This might work like http://unitsofmeasurement.github.io/unit-api/site/apidocs/index.html (using the https://github.com/unitsofmeasurement/unit-api/tree/gh-pages branch) but please note there's a bit of a **caveat** since the GH Maven plugins kept causing GitHub's "abuse warning" all the time if pushed via a Maven goal (even a manual one, not talking of a CI job) so I stick to manual pushes. Would be happy to see GH fixing it, but maybe it requires a corporate subscription or similar? ;-/

**Pull request merged**
