### PR TITLE
Fix import of java.util.Objects

### PR DESCRIPTION
**Pull request by sameer-pandit**
build fails, import java.util.Objects.

### CODE REVIEW

**Comment by wmhopkins** [comment]
@sameer-pandit Thanks for fixing this. People should probably compile the code before submitting a change ... ;)

You're an Oracle employee, so I think it should be fine for you to submit changes, but just want to check first with the EE team to ask whether you should also join the EG contributor as a contributor.

**Comment by sameer-pandit** [comment]
sure @wmhopkins , I am fine with even you submitting change via another pull request. I had to do this change for my local test setup, so I thought I will just raise PR.

**Comment by ggam** [comment]
This was my fault, sorry. I thought the Objects class was on java.lang
package (so it wouldn't have to be imported) and that a CI was already
checking. It was such a simple change that I did it directly from the
GitHub UI.

I promise I'll test it next time :(

**Comment by wmhopkins** [comment]
No worries @ggam ;)

@sameer-pandit, we're fine to accept code from Oracle employees as long as it's our IP. Will merge it now.

**Pull request merged**
