### PR TITLE
Populate new repo with API code

### PR DESCRIPTION
**Pull request by wmhopkins**
I've taken the "api" module from the soteria repository and checked it in as "src" (along with a copy of the license source). I did my best to merge the api and parent pom.xml files, but may not have gotten everything right. I also notice there's a mvn error caused by not specifying a version for one of the plugins; as far as I can tell that's not a new error. I'm also wondering why there's test code for the API, given that it's all interface, not implementation.

### CODE REVIEW

**Comment by keilw** [comment]
Thanks. Will have a closer look tomorrow when I'm in the office, but looks good at first sight.
If the "jvnet-parent" was beneficial to the API or not can't say, but some parent POM could be OK there, too. Even if java.net goes away, the POM won't vanish if it is also on MavenCentral.

`inceptionYear` is commented out. It may give trouble to the license plugin, at least when regenerating headers, potentially even during normal build when it tries to compare with headers.

Let's also see, what @arjantijms says. Werner

**Comment by wmhopkins** [comment]
Arjan hasn't commented, so I'm just going to go ahead and submit. I did move the jvnet-parent and inceptionYear out of comments; we can fix any remaining issues later.

**Comment by arjantijms** [comment]
Hi, sorry for not commenting before. Have been extremely busy. Without looking at the move, the test code (in the /test module) are high level IT tests, not API specific tests.

The API is indeed mostly API, although it's hard to escape having a few trivial implementation things here and there (in order to not make things too obscure). I've asked about this before, whether we want a 100% pure API (100% only interfaces, enums, and such), or allow a tiny bit of trivial implementation.

We can likely still change this if the opinions on this have changed.

**Comment by keilw** [comment]
Since we use Java SE 8 as a minimum version here, there is no reason against an interface. If you need a "default implementation" we can use `default` methods.

**Comment by arjantijms** [comment]
Absolutely, that takes care of 90% of the need, but there's still a couple of cases where you need trivial state, such as in https://github.com/javaee-security-spec/security-api/blob/master/src/main/java/javax/security/CallerPrincipal.java

Sure, we can make it an interface again, but that would require the user instantiating it to implement a trivial implementation first.

I remember we discussed this and back then it was decided to make `CallerPrincipal` a concrete class here.

**Comment by keilw** [comment]
As long as it's not a `final` class, something that would only make sense in very few cases, e.g. some factory that should not be extended.

Btw, at least in Java SE I remember there are no "author" tags in most Oracle led projects. How about this JSR? @wmhopkins Do you know, if authors are OK or not?

**Comment by arjantijms** [comment]
We recently removed a bunch of author tags in JSR 372, but historical ones are still there. Java SE historical code has them as well.

**Comment by keilw** [comment]
Since we just started populating the actual API there is not that much "historical code" in JSR 375. JSF has a long history, so probably different there.

**Pull request merged**
