### PR TITLE
SecurityContext javadoc fixes

### PR DESCRIPTION
**Pull request by ggam**

### CODE REVIEW

**Comment by arjantijms** [comment]
+1 as well ;)

**Comment by keilw** [comment]
+1

**Comment by arjantijms** [comment]
@keilw No all we need is write access and we can merge it in ;)

**Comment by ggam** [comment]
Btw, JavaDoc says that this class must be usable on any Java EE container, explicitly mentioning, while the spec PDF says it is only required to work on Servlet and EJB.

It was finally decided to require it to work everywhere, no?

**Comment by arjantijms** [comment]
>It was finally decided to require it to work everywhere, no?

Indeed

**Comment by ggam** [comment]
Thanks @arjantijms. PR sent javaee-security-spec/security-spec/pull/6

What do you think about removing the note about EJB and Servlet containers? I see it redundant and confusing. If it has to work in all containers, that obviously include EJB and Servlet. That note can be interpreted as the "all should be supported, only these are really required".

**Comment by arjantijms** [comment]
It's more or less a clarification, if someone may not get exactly what "container" is in this context. The word is a bit overloaded and is sometimes meant to refer to the entire server.

**Comment by ggam** [comment]
You're right. How about this?
> When running on a Java EE Application Server, and unless otherwise indicated, this type must be usable in all Java EE containers, including the Servlet and EJB containers.

**Comment by arjantijms** [comment]
+1 ;)

**Comment by wmhopkins** [comment]
It's not reasonable to say SecurityContext must be present in all containers without enumerating the containers in question and verifying that there is a reasonable implementation for all relevant SecurityContext methods in each container.

Closing this PR (and the one in security-spec) and moving discussion to the list.

**Pull request closed without merging**
